"""add_config_columns

Revision ID: 4473261568f1
Revises: 41ebd3424b77
Create Date: 2025-11-06 14:28:12.334188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4473261568f1'
down_revision: Union[str, Sequence[str], None] = '41ebd3424b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('base_config', sa.JSON(), nullable=True))
    op.add_column('devices', sa.Column('service_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'service_config')
    op.drop_column('devices', 'base_config')
    # ### end Alembic commands ###
