"""Add performance indexes to device table

Revision ID: 765ea0a2347c
Revises: 93809db17d91
Create Date: 2025-11-09 17:23:12.991893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '765ea0a2347c'
down_revision: Union[str, Sequence[str], None] = '93809db17d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_devices_status'), 'devices', ['status'], unique=False)
    op.create_index(op.f('ix_devices_timestamp'), 'devices', ['timestamp'], unique=False)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_index('ix_status_timestamp', 'devices', ['status', 'timestamp'], unique=False)
    op.create_index('ix_user_status', 'devices', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_status', table_name='devices')
    op.drop_index('ix_status_timestamp', table_name='devices')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_timestamp'), table_name='devices')
    op.drop_index(op.f('ix_devices_status'), table_name='devices')
    # ### end Alembic commands ###
