"""Add lock and ntrip status fields

Revision ID: 93809db17d91
Revises: 4473261568f1
Create Date: 2025-11-08 21:05:19.459870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93809db17d91'
down_revision: Union[str, Sequence[str], None] = '4473261568f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('ntrip_connected', sa.Boolean(), nullable=True))
    op.add_column('devices', sa.Column('ntrip_status', sa.JSON(), nullable=True))
    op.add_column('devices', sa.Column('is_locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'is_locked')
    op.drop_column('devices', 'ntrip_status')
    op.drop_column('devices', 'ntrip_connected')
    # ### end Alembic commands ###
